spring:

  main:
    banner-mode: off
  servlet:
    multipart:
      max-request-size: 5GB
      max-file-size: 5GB
  datasource:
    url: jdbc:mysql://localhost:3307/HIT_LEARNING?createDatabaseIfNotExist=true
    username: ${database.username}
    password: ${database.password}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        search:
          backend:
            analysis:
              configurer: com.example.hit_learning.config.ElasticSearchConfig
          schema_management:
            strategy: create-or-update

    show-sql: false
server:
  error:
    include-message: always
  servlet:
    context-path: /hit-learning



